export const ADD_REMINDER = "ADD_REMINDER";
export const DELETE_REMINDER = "DELETE_REMINDER";
export const DELETE_DAY_REMINDERS = "DELETE_DAY_REMINDERS";
export const EDIT_REMINDER = "EDIT_REMINDER";
export const WEATHER = "WEATHER";